### ISSUE TITLE
The old morseCode bug is back

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/CrewLight#1]
I do as the OP of this forum thread says how to change the morse code string and it appears inside the persistent.sfs and is good for a while.
But after exiting the game and continuing the save later, the setting is back to default.

After loading KSP to the main menu and then loading the save I find this in the log:
```
Exception handling event OnGameSettingsApplied in class GameSettingsLive:System.NullReferenceException: Object reference not set to an instance of an object
  at CrewLight.GameSettingsLive.SettingsApplied () [0x00000] in <0084462673bb487e8e32fc1e27ee5556>:0
  at EventVoid.Fire () [0x00127] in <cd473063d3a2482f8d93d388d0c95035>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at CrewLight.GameSettingsLive.SettingsApplied () [0x00000] in <0084462673bb487e8e32fc1e27ee5556>:0
  at EventVoid.Fire () [0x00127] in <cd473063d3a2482f8d93d388d0c95035>:0
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
EventVoid:Fire()
KSP.UI.Screens.Settings.SettingsScreen:OnApply()
KSP.UI.Screens.Settings.SettingsScreen:OnAccept()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: <0084462673bb487e8e32fc1e27ee5556> Line: 0)
```

**Comment by linuxgurugamer** [comment]
Thanks, will take a look at this, along with possibly putting the settings into a local file

**Comment by linuxgurugamer** [comment]
However, I would have liked to have seen the entire log file, I have some questions which force me to replicate this before fixing it

**Comment by linuxgurugamer** [comment]
Please post the complete log, I can't seem to get it to fail

**Comment by linuxgurugamer** [comment]
Try this file, I added a check to make sure the game was actually in a save, this will prevent that nullref

[CrewLight-1.20.0.2.zip](https://github.com/linuxgurugamer/CrewLight/files/7493316/CrewLight-1.20.0.2.zip)

**Comment by Gordon-Dry** [comment]
Sieht gut aus.

**Comment by linuxgurugamer** [comment]
Ummm, google translate said it looks good?

**Comment by Gordon-Dry** [comment]
Oh yes, sorry, I was "slightly" distracted by a ton of open tabs in my browser session.

**Comment by linuxgurugamer** [comment]
That's ok.  Not going to release it right away, so I'll leave this open.  I want to fix the screwy method to open the more settings window, and maybe add a letter to morse translation to make it easier to enter messages.

**Comment by linuxgurugamer** [comment]
Wondering if you can check this out:
https://www.dropbox.com/s/xr67mby7skq0gfb/CrewLight-1.20.0.2.zip?dl=0

This is a list of all the changes, the first one is in the fix I already gave you:

- 	Added check in SettingsApplied() to make sure actually in a game to avoid a nullref
- 	Added text entry field to enter text and have it translated to Morse code
- 	Removed silly way to open the More Morse window, now it opens when the More Morse radio button is toggled.  If not closed More Morse window will stay open until the settings screen is exited
- 	Hard-coded layout in More Morse window

**Comment by Gordon-Dry** [comment]
I will.
btw if you change the Dropbox link to have =1 at the end it will be a direct download link.

**Comment by linuxgurugamer** [comment]
yeah, I know, but when I get the link, it does it as a 0, and I usually forget to change it

Thanks

**Comment by Gordon-Dry** [comment]
It does well. Now I need to see if it stays persistent without issues.

**Comment by linuxgurugamer** [comment]
How do you like the new feature to make the morse code automatically?

**Comment by Gordon-Dry** [comment]
It's a QOL feature of course.
